//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public string Name { get; set; }
        public string aliases { get; set; }
        public string type { get; set; }
        public string ISO_codes { get; set; }
        public Nullable<System.DateTime> begin_Dates { get; set; }
        public Nullable<System.DateTime> end_dates { get; set; }
        public string disambiguation_comment { get; set; }
        public int MBID { get; set; }
    }
}
