//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public string Name { get; set; }
        public string sort_name { get; set; }
        public string areas { get; set; }
        public string IPI { get; set; }
        public string ISNI { get; set; }
        public string aliases { get; set; }
        public string Artist_type { get; set; }
        public Nullable<System.DateTime> begin_dates { get; set; }
        public Nullable<System.DateTime> End_dates { get; set; }
        public string disambiguation_comment { get; set; }
        public int MBID { get; set; }
    }
    public class StoredProc
    {
        public string name { get; set; }
        public string title { get; set; }
        public string album { get; set; }
    }
}
