//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recording
    {
        public string Title { get; set; }
        public string artist_credit { get; set; }
        public string duration { get; set; }
        public string ISRC { get; set; }
        public string PUIDs { get; set; }
        public string disambiguation_comment { get; set; }
        public Nullable<int> MBID { get; set; }
        public int recordid { get; set; }
    }
}
